target_sources(SPIRV-Tools-opt
  PRIVATE
    #/source/opt
    ${SPIRV-Tools-Dir}/source/opt/aggressive_dead_code_elim_pass.cpp
    ${SPIRV-Tools-Dir}/source/opt/aggressive_dead_code_elim_pass.h
    ${SPIRV-Tools-Dir}/source/opt/basic_block.cpp
    ${SPIRV-Tools-Dir}/source/opt/basic_block.h
    ${SPIRV-Tools-Dir}/source/opt/block_merge_pass.cpp
    ${SPIRV-Tools-Dir}/source/opt/block_merge_pass.h
    ${SPIRV-Tools-Dir}/source/opt/build_module.cpp
    ${SPIRV-Tools-Dir}/source/opt/build_module.h
    ${SPIRV-Tools-Dir}/source/opt/ccp_pass.cpp
    ${SPIRV-Tools-Dir}/source/opt/ccp_pass.h
    ${SPIRV-Tools-Dir}/source/opt/cfg.cpp
    ${SPIRV-Tools-Dir}/source/opt/cfg.h
    ${SPIRV-Tools-Dir}/source/opt/cfg_cleanup_pass.cpp
    ${SPIRV-Tools-Dir}/source/opt/cfg_cleanup_pass.h
    ${SPIRV-Tools-Dir}/source/opt/combine_access_chains.cpp
    ${SPIRV-Tools-Dir}/source/opt/combine_access_chains.h
    ${SPIRV-Tools-Dir}/source/opt/common_uniform_elim_pass.cpp
    ${SPIRV-Tools-Dir}/source/opt/common_uniform_elim_pass.h
    ${SPIRV-Tools-Dir}/source/opt/compact_ids_pass.cpp
    ${SPIRV-Tools-Dir}/source/opt/compact_ids_pass.h
    ${SPIRV-Tools-Dir}/source/opt/composite.cpp
    ${SPIRV-Tools-Dir}/source/opt/composite.h
    ${SPIRV-Tools-Dir}/source/opt/constants.cpp
    ${SPIRV-Tools-Dir}/source/opt/constants.h
    ${SPIRV-Tools-Dir}/source/opt/const_folding_rules.cpp
    ${SPIRV-Tools-Dir}/source/opt/const_folding_rules.h
    ${SPIRV-Tools-Dir}/source/opt/copy_prop_arrays.cpp
    ${SPIRV-Tools-Dir}/source/opt/copy_prop_arrays.h
    ${SPIRV-Tools-Dir}/source/opt/dead_branch_elim_pass.cpp
    ${SPIRV-Tools-Dir}/source/opt/dead_branch_elim_pass.h
    ${SPIRV-Tools-Dir}/source/opt/dead_insert_elim_pass.cpp
    ${SPIRV-Tools-Dir}/source/opt/dead_insert_elim_pass.h
    ${SPIRV-Tools-Dir}/source/opt/dead_variable_elimination.cpp
    ${SPIRV-Tools-Dir}/source/opt/dead_variable_elimination.h
    ${SPIRV-Tools-Dir}/source/opt/decoration_manager.cpp
    ${SPIRV-Tools-Dir}/source/opt/decoration_manager.h
    ${SPIRV-Tools-Dir}/source/opt/def_use_manager.cpp
    ${SPIRV-Tools-Dir}/source/opt/def_use_manager.h
    ${SPIRV-Tools-Dir}/source/opt/dominator_analysis.cpp
    ${SPIRV-Tools-Dir}/source/opt/dominator_analysis.h
    ${SPIRV-Tools-Dir}/source/opt/dominator_tree.cpp
    ${SPIRV-Tools-Dir}/source/opt/dominator_tree.h
    ${SPIRV-Tools-Dir}/source/opt/eliminate_dead_constant_pass.cpp
    ${SPIRV-Tools-Dir}/source/opt/eliminate_dead_constant_pass.h
    ${SPIRV-Tools-Dir}/source/opt/eliminate_dead_functions_pass.cpp
    ${SPIRV-Tools-Dir}/source/opt/eliminate_dead_functions_pass.h
    ${SPIRV-Tools-Dir}/source/opt/feature_manager.cpp
    ${SPIRV-Tools-Dir}/source/opt/feature_manager.h
    ${SPIRV-Tools-Dir}/source/opt/flatten_decoration_pass.cpp
    ${SPIRV-Tools-Dir}/source/opt/flatten_decoration_pass.h
    ${SPIRV-Tools-Dir}/source/opt/fold.cpp
    ${SPIRV-Tools-Dir}/source/opt/fold.h
    ${SPIRV-Tools-Dir}/source/opt/folding_rules.cpp
    ${SPIRV-Tools-Dir}/source/opt/folding_rules.h
    ${SPIRV-Tools-Dir}/source/opt/fold_spec_constant_op_and_composite_pass.cpp
    ${SPIRV-Tools-Dir}/source/opt/fold_spec_constant_op_and_composite_pass.h
    ${SPIRV-Tools-Dir}/source/opt/freeze_spec_constant_value_pass.cpp
    ${SPIRV-Tools-Dir}/source/opt/freeze_spec_constant_value_pass.h
    ${SPIRV-Tools-Dir}/source/opt/function.cpp
    ${SPIRV-Tools-Dir}/source/opt/function.h
    ${SPIRV-Tools-Dir}/source/opt/if_conversion.cpp
    ${SPIRV-Tools-Dir}/source/opt/if_conversion.h
    ${SPIRV-Tools-Dir}/source/opt/inline_exhaustive_pass.cpp
    ${SPIRV-Tools-Dir}/source/opt/inline_exhaustive_pass.h
    ${SPIRV-Tools-Dir}/source/opt/inline_opaque_pass.cpp
    ${SPIRV-Tools-Dir}/source/opt/inline_opaque_pass.h
    ${SPIRV-Tools-Dir}/source/opt/inline_pass.cpp
    ${SPIRV-Tools-Dir}/source/opt/inline_pass.h
    ${SPIRV-Tools-Dir}/source/opt/instruction.cpp
    ${SPIRV-Tools-Dir}/source/opt/instruction.h
    ${SPIRV-Tools-Dir}/source/opt/instruction_list.cpp
    ${SPIRV-Tools-Dir}/source/opt/instruction_list.h
    ${SPIRV-Tools-Dir}/source/opt/instrument_pass.cpp
    ${SPIRV-Tools-Dir}/source/opt/instrument_pass.h
    ${SPIRV-Tools-Dir}/source/opt/inst_bindless_check_pass.cpp
    ${SPIRV-Tools-Dir}/source/opt/inst_bindless_check_pass.h
    ${SPIRV-Tools-Dir}/source/opt/ir_builder.h
    ${SPIRV-Tools-Dir}/source/opt/ir_context.cpp
    ${SPIRV-Tools-Dir}/source/opt/ir_context.h
    ${SPIRV-Tools-Dir}/source/opt/ir_loader.cpp
    ${SPIRV-Tools-Dir}/source/opt/ir_loader.h
    ${SPIRV-Tools-Dir}/source/opt/iterator.h
    ${SPIRV-Tools-Dir}/source/opt/licm_pass.cpp
    ${SPIRV-Tools-Dir}/source/opt/licm_pass.h
    ${SPIRV-Tools-Dir}/source/opt/local_access_chain_convert_pass.cpp
    ${SPIRV-Tools-Dir}/source/opt/local_access_chain_convert_pass.h
    ${SPIRV-Tools-Dir}/source/opt/local_redundancy_elimination.cpp
    ${SPIRV-Tools-Dir}/source/opt/local_redundancy_elimination.h
    ${SPIRV-Tools-Dir}/source/opt/local_single_block_elim_pass.cpp
    ${SPIRV-Tools-Dir}/source/opt/local_single_block_elim_pass.h
    ${SPIRV-Tools-Dir}/source/opt/local_single_store_elim_pass.cpp
    ${SPIRV-Tools-Dir}/source/opt/local_single_store_elim_pass.h
    ${SPIRV-Tools-Dir}/source/opt/local_ssa_elim_pass.cpp
    ${SPIRV-Tools-Dir}/source/opt/local_ssa_elim_pass.h
    ${SPIRV-Tools-Dir}/source/opt/log.h
    ${SPIRV-Tools-Dir}/source/opt/loop_dependence.cpp
    ${SPIRV-Tools-Dir}/source/opt/loop_dependence.h
    ${SPIRV-Tools-Dir}/source/opt/loop_dependence_helpers.cpp
    ${SPIRV-Tools-Dir}/source/opt/loop_descriptor.cpp
    ${SPIRV-Tools-Dir}/source/opt/loop_descriptor.h
    ${SPIRV-Tools-Dir}/source/opt/loop_fission.cpp
    ${SPIRV-Tools-Dir}/source/opt/loop_fission.h
    ${SPIRV-Tools-Dir}/source/opt/loop_fusion.cpp
    ${SPIRV-Tools-Dir}/source/opt/loop_fusion.h
    ${SPIRV-Tools-Dir}/source/opt/loop_fusion_pass.cpp
    ${SPIRV-Tools-Dir}/source/opt/loop_fusion_pass.h
    ${SPIRV-Tools-Dir}/source/opt/loop_peeling.cpp
    ${SPIRV-Tools-Dir}/source/opt/loop_peeling.h
    ${SPIRV-Tools-Dir}/source/opt/loop_unroller.cpp
    ${SPIRV-Tools-Dir}/source/opt/loop_unroller.h
    ${SPIRV-Tools-Dir}/source/opt/loop_unswitch_pass.cpp
    ${SPIRV-Tools-Dir}/source/opt/loop_unswitch_pass.h
    ${SPIRV-Tools-Dir}/source/opt/loop_utils.cpp
    ${SPIRV-Tools-Dir}/source/opt/loop_utils.h
    ${SPIRV-Tools-Dir}/source/opt/mem_pass.cpp
    ${SPIRV-Tools-Dir}/source/opt/mem_pass.h
    ${SPIRV-Tools-Dir}/source/opt/merge_return_pass.cpp
    ${SPIRV-Tools-Dir}/source/opt/merge_return_pass.h
    ${SPIRV-Tools-Dir}/source/opt/module.cpp
    ${SPIRV-Tools-Dir}/source/opt/module.h
    ${SPIRV-Tools-Dir}/source/opt/null_pass.h
    ${SPIRV-Tools-Dir}/source/opt/optimizer.cpp
    ${SPIRV-Tools-Dir}/source/opt/pass.cpp
    ${SPIRV-Tools-Dir}/source/opt/pass.h
    ${SPIRV-Tools-Dir}/source/opt/passes.h
    ${SPIRV-Tools-Dir}/source/opt/pass_manager.cpp
    ${SPIRV-Tools-Dir}/source/opt/pass_manager.h
    ${SPIRV-Tools-Dir}/source/opt/pch_source_opt.cpp
    ${SPIRV-Tools-Dir}/source/opt/pch_source_opt.h
    ${SPIRV-Tools-Dir}/source/opt/private_to_local_pass.cpp
    ${SPIRV-Tools-Dir}/source/opt/private_to_local_pass.h
    ${SPIRV-Tools-Dir}/source/opt/process_lines_pass.cpp
    ${SPIRV-Tools-Dir}/source/opt/process_lines_pass.h
    ${SPIRV-Tools-Dir}/source/opt/propagator.cpp
    ${SPIRV-Tools-Dir}/source/opt/propagator.h
    ${SPIRV-Tools-Dir}/source/opt/reduce_load_size.cpp
    ${SPIRV-Tools-Dir}/source/opt/reduce_load_size.h
    ${SPIRV-Tools-Dir}/source/opt/redundancy_elimination.cpp
    ${SPIRV-Tools-Dir}/source/opt/redundancy_elimination.h
    ${SPIRV-Tools-Dir}/source/opt/reflect.h
    ${SPIRV-Tools-Dir}/source/opt/register_pressure.cpp
    ${SPIRV-Tools-Dir}/source/opt/register_pressure.h
    ${SPIRV-Tools-Dir}/source/opt/remove_duplicates_pass.cpp
    ${SPIRV-Tools-Dir}/source/opt/remove_duplicates_pass.h
    ${SPIRV-Tools-Dir}/source/opt/replace_invalid_opc.cpp
    ${SPIRV-Tools-Dir}/source/opt/replace_invalid_opc.h
    ${SPIRV-Tools-Dir}/source/opt/scalar_analysis.cpp
    ${SPIRV-Tools-Dir}/source/opt/scalar_analysis.h
    ${SPIRV-Tools-Dir}/source/opt/scalar_analysis_nodes.h
    ${SPIRV-Tools-Dir}/source/opt/scalar_analysis_simplification.cpp
    ${SPIRV-Tools-Dir}/source/opt/scalar_replacement_pass.cpp
    ${SPIRV-Tools-Dir}/source/opt/scalar_replacement_pass.h
    ${SPIRV-Tools-Dir}/source/opt/set_spec_constant_default_value_pass.cpp
    ${SPIRV-Tools-Dir}/source/opt/set_spec_constant_default_value_pass.h
    ${SPIRV-Tools-Dir}/source/opt/simplification_pass.cpp
    ${SPIRV-Tools-Dir}/source/opt/simplification_pass.h
    ${SPIRV-Tools-Dir}/source/opt/ssa_rewrite_pass.cpp
    ${SPIRV-Tools-Dir}/source/opt/ssa_rewrite_pass.h
    ${SPIRV-Tools-Dir}/source/opt/strength_reduction_pass.cpp
    ${SPIRV-Tools-Dir}/source/opt/strength_reduction_pass.h
    ${SPIRV-Tools-Dir}/source/opt/strip_debug_info_pass.cpp
    ${SPIRV-Tools-Dir}/source/opt/strip_debug_info_pass.h
    ${SPIRV-Tools-Dir}/source/opt/strip_reflect_info_pass.cpp
    ${SPIRV-Tools-Dir}/source/opt/strip_reflect_info_pass.h
    ${SPIRV-Tools-Dir}/source/opt/struct_cfg_analysis.cpp
    ${SPIRV-Tools-Dir}/source/opt/struct_cfg_analysis.h
    ${SPIRV-Tools-Dir}/source/opt/tree_iterator.h
    ${SPIRV-Tools-Dir}/source/opt/types.cpp
    ${SPIRV-Tools-Dir}/source/opt/types.h
    ${SPIRV-Tools-Dir}/source/opt/type_manager.cpp
    ${SPIRV-Tools-Dir}/source/opt/type_manager.h
    ${SPIRV-Tools-Dir}/source/opt/unify_const_pass.cpp
    ${SPIRV-Tools-Dir}/source/opt/unify_const_pass.h
    ${SPIRV-Tools-Dir}/source/opt/value_number_table.cpp
    ${SPIRV-Tools-Dir}/source/opt/value_number_table.h
    ${SPIRV-Tools-Dir}/source/opt/vector_dce.cpp
    ${SPIRV-Tools-Dir}/source/opt/vector_dce.h
    ${SPIRV-Tools-Dir}/source/opt/workaround1209.cpp
    ${SPIRV-Tools-Dir}/source/opt/workaround1209.h
)
